apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    family: bry-fw2
    release: prometheus-operator
  name: fw2-service-monitor
spec:
  endpoints:
  - interval: 10s
    path: /actuator/prometheus
    port: web
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      family: bry-fw2
